spring:
    config:
        activate:
            on-profile: dev
    jpa:
        hibernate:
            ddl-auto: update
    data:
        redis:
            port: 6379
            host: localhost
    security:
        oauth2: # OAuth2 설정
            client:
                registration:
                    kakao:
                        client-id: ENC(Xwe+n+BcSACdwzJVkC3+LjEIc0E2lFyiQrmVAwW1al1wKrjH8/7v0SfeWNsMortF)
                        client-secret: ENC(KMznWHuXZSn9bJeaFoiFz+JMlf7VlTnQOZ0Rof+yUpw+xaSp0RRFkOQzRNNVczGs)
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        client-name: Kakao
                        redirect-uri: ENC(wOF33L11fMcktVG58gsI2myTIg9PG7N9mNXkLkXrQ4URpKpcA3ovcEW9XwXGvHYlf8lSwjx2dwo=)
                    naver:
                        client-id: ENC(Y4w25dgNj0KENqeegLzHemOhIkTJjO/NTIDSBZdQT6U=)
                        client-secret: ENC(kDJs39qNCyUbeoIH0PDf9pYV9umo4Opm)
                        authorization-grant-type: authorization_code
                        client-name: Naver
                        redirect-uri: ENC(NdkqvNBa9vDKXfXzEMyTe0GQqINfw1LgEALpMqj2JsuQImI7S89eUMwOC5DOidypci/GeZcQ3j4=)
                    google:
                        client-id: ENC(wqDdvw9UfJcUUS9xe4rgkQY7CQWSNeyE4wVXwo81knU11bDMwDr3ZHpgwKjT5w1WoMWua6PqEMOMyIR3thONh8hycohCHZpq8pE80OiRV3XRjHS5ApQ8FQ==)
                        client-secret: ENC(gbBRQPxmr0EurTrL8OXYnjrzTuKIa5LdM3VyGaXJa41EjlcFMy5o/6lYGW0N5GzY)
                        redirect-uri: ENC(wEMvaB7smiTI5eSTvHWXFv+PiqXyXM+DUVTED6nykPY/+79wtNIAve1BY0VntjXntUm1mAcESf8=)
                        scope:
                            - email
                            - profile
                    github:
                        client-id: ENC(TTDnGSDlZxzhLwP5TruzOb+i+grccHO4Q6isocFnSrk=)
                        client-secret: ENC(YbbWG1/3mq6hgHZlK7mF8BuuhZeI8tfg5AEZnH9C9y4ZxUfIuguFtzwUXbyIFEBdAHHbmuP2mGw=)
                        redirect-uri: ENC(9pGMq070Ocwdj3AtpeVQSdfvUKpr1EWTiGlripeYfKBpKDgzQpgtN2V3URSpsFKmK+arsMA1MXg=)
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
            redirect-url: ENC(dgPWuJGVsturvARrC9zLCCPAfxhh8Y0j98CYwTk3ttI=)

