spring:
    config:
        activate:
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: none
    data:
        redis:
            port: 6379
            host: algopuni-redis-001.f2xyi1.0001.apn2.cache.amazonaws.com:6379
    security:
        oauth2: # OAuth2 설정
            client:
                registration:
                    kakao:
                        client-id: ENC(Xwe+n+BcSACdwzJVkC3+LjEIc0E2lFyiQrmVAwW1al1wKrjH8/7v0SfeWNsMortF)
                        client-secret: ENC(KMznWHuXZSn9bJeaFoiFz+JMlf7VlTnQOZ0Rof+yUpw+xaSp0RRFkOQzRNNVczGs)
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        client-name: Kakao
                        redirect-uri: ENC(PhVvBoGaiPwGnimz1MqjQhnX7sqAjpv61ieP0END/QIMIHSdmahkPDDBk0/cwIIgzl7onSVbGTieOwa+lGhQZw==)
                    naver:
                        client-id: ENC(Y4w25dgNj0KENqeegLzHemOhIkTJjO/NTIDSBZdQT6U=)
                        client-secret: ENC(kDJs39qNCyUbeoIH0PDf9pYV9umo4Opm)
                        authorization-grant-type: authorization_code
                        client-name: Naver
                        redirect-uri: ENC(/S8t4HJ2jReDlD1hNokQh6uxTwxv4MxW+H/Ro21Jqky8OkyGBtnzo5lNNOkbJSEPCaO/kSu8yeiuWlL286Khsw==)
                    google:
                        client-id: ENC(CYE0ce1JZZhgTzcQN+qTsF7MpJ8CU+fjRFh4q6hdPLwDGpo5owIWQ/Xk9LwxWzhTLYJQNiKBdr1Bcb2lmDYkWocqrKuCBoPqIKuJhhb2FrC3Ak63YSVtiA==)
                        client-secret: ENC(NvAQcfvu15yPdDJFJ1Jnr6GYqx3cGMFlr/ruT5OlnTfP7R90A316meMuQ2ERgIda)
                        redirect-uri: ENC(iuBXLH2+YenqGEzt1tbhcradAt5SM8n8UkrqXjzlP5ZIYMi7MkIbyzlghlPjMuk2z2rFGw8zuKeaZuJkW/eYOw==)
                        scope:
                            - email
                            - profile
                    github:
                        client-id: ENC(pbfARF3FNvUxZivtiI+MgX0u+hbFkwNe9TXwxNBPoyg=)
                        client-secret: ENC(SkGbk9YYPNc737WJUBWLpkR7UlVuwbr/O+3weYwZc4uDN+4PMeTBaf9JiYYOPSbMHV8h4o63N1w=)
                        redirect-uri: ENC(gdXxW5WEsVWWOJ2IWBkqlBMjQACtI4RFLGn5AprRrdBotprZ7aZu8VcRi0WbZ3yEBySNlU9su+zWt+vHhoqQMw==)
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
            redirect-url: ENC(u/ieXyKGH47hBMsiM4IerFWPSPnpTz+dzbYb+9OVntkc50xMxhIVGg==)